apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: football-analytics
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'football-api'
      static_configs:
      - targets: ['football-api:8000']
      metrics_path: /metrics
    - job_name: 'postgres'
      static_configs:
      - targets: ['postgres-exporter:9187']